ehPasar/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('wishlist.urls')),
    path('', include('listfavorit.urls')),
    path('', include('signup.urls')),
    path('', include('cari_pasar.urls')),
    path('', include('detailBarang.urls')),
    path('', include('listBarang.urls')),
    path('feedback/', include('feedback.urls')),
    path('', include('manajemenpasar.urls')),
]

listfavorit/urls.py
from django.urls import path
from . import views

app_name='listfavorit'

urlpatterns = [
    path('listfavorit/', views.listfavorit, name='listfavorit'),
    path('listfavorit/<int:idBarang>', views.detailListFavorit, name='detailListFavorit'),
    path('listfavorit/add/<int:idBarang>/', views.addListFavorit, name='addListFavorit'),
    path('listfavorit/delete/<int:idBarang>/', views.deleteListFavorit, name='deleteListFavorit'),
    path('checkout/', views.checkout, name='checkout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

signup/urls.py
from django.urls import path
from . import views

app_name='signup'

urlpatterns = [
    path('signup', views.daftar, name='daftar'),
    path('coba', views.coba, name='coba'),
    path('masuk', views.signup, name='signup'),
    path('sign_in', views.signin, name='sign_in'),
    path('sign_out', views.signOut, name='sign_out'),
]

wishlist/urls.py
from django.urls import path
from . import views

app_name='wishlist'

urlpatterns = [
    path('wishlist/', views.getWishlist, name='wishlist'),
    path('add_wishlist/<int:barang_id>/', views.insertBarangWishlist, name='add_wishlist'),
    path('wishlist/detail_wishlist/<int:barang_id>/', views.detail_wishlist, name='detail_wishlist'),
    path('detele_wishlist/<int:barang_id>/', views.removeBarangWishlist, name='delete_wishlist'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block title %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm p-3 mb-5" id="navigation" style='background-color: white;'>
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">ehPasar</a>
        <!--<a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'img/.png' %}" alt="" id="logo">
        </a>-->
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            
            <a class="nav-link nav-item" href="{% url 'signup:sign_in' %}">Sign In</a>
            
            <a href="{% url 'signup:signup' %}"><button type="button" class="btn btn-primary" style="background-color: #98D5CD;outline-color: #98D5CD;color: black;">Sign Up</button></a>
            
            
        </div>
    </div>
    </nav>
{% block content %}


{% endblock %}
</body>



</html>

templates/navbar_1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block title %}

    {% endblock %}
    <style>
        .logo{
            width: 25px;
            height: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm p-3 mb-5" id="navigation" style='background-color: white;'>
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">ehPasar</a>
        <!--<a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'img/.png' %}" alt="" id="logo">
        </a>-->
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            {% block nav %}
            <a class="nav-link nav-item" href="#">History</a>
            <a class="nav-link nav-item" href="{% url 'wishlist:wishlist' %}">Wishlist</a>
            <a class="nav-link nav-item" href="{% url 'listfavorit:listfavorit' %}">List Favorit</a>
            <a class="nav-link nav-item" href="#"><img src="{% static 'img/Keranjang.jpg' %}" alt="" class="logo"></a>
            <a class="nav-link nav-item" >Halo, {{ user.nama }}</a>
            <a class="nav-link nav-item" href="{% url 'signup:sign_out' %}">Sign out</a>
            {% endblock %}
        </div>
    </div>
    </nav>
{% block content %}


{% endblock %}
<script>
    window.onscroll = function() {myFunction()};
    
    var navbar = document.getElementById("navigation");
    var sticky = navbar.offsetTop;
    
    function myFunction() {
      if (window.pageYOffset >= sticky) {
        navbar.classList.add("sticky")
      } else {
        navbar.classList.remove("sticky");
      }
    }
    </script>
</body>
</html>