detailBarang/urls.py
from django.urls import re_path, path
from .views import detailBarang

urlpatterns = [
    path('catalog/detailBarang/<int:barang_id>/', detailBarang, name='barang'),

]

ehPasar/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('wishlist.urls')),
    path('', include('listfavorit.urls')),
    path('', include('signup.urls')),
    path('', include('cari_pasar.urls')),
    path('', include('detailBarang.urls')),
    path('', include('listBarang.urls')),
    path('feedback/', include('feedback.urls')),
    path('', include('manajemenpasar.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

manajemenpasar/urls.py
from django.urls import path
from . import views

app_name='manajemenpasar'

urlpatterns = [
    path('manajemenpasar/', views.index, name='index'),
    path('manajemenpasar/tambahbarang/', views.createbarang, name='createbarang'),
    path('manajemenpasar/<int:detail_id>/', views.detailbarang, name='detailbarang'),
    path('manajemenpasar/deletebarang/<int:delete_id>/', views.deletebarang, name='deletebarang'),
    path('manajemenpasar/updatebarang/<int:update_id>/', views.updatebarang, name='updatebarang'),
]

detailBarang/models.py
from django.db import models

# Create your models here.
class Barang(models.Model):
    id = models.AutoField(primary_key=True)
    namaBarang = models.CharField(max_length=100)
    jumlahStok = models.PositiveIntegerField()
    hargaBarang = models.PositiveIntegerField()
    deskripsiBarang = models.CharField(max_length=300)
    def __str__(self):
        return self.namaBarang

manajemenpasar/models.py
from django.db import models

# Create your models here.

manajemenpasar/forms.py
from django.db.models import fields
from django.forms.models import ModelForm
from detailBarang.models import Barang
from django import forms

class BarangForm(ModelForm):
    class Meta:
        model = Barang
        fields = ['namaBarang', 'jumlahStok', 'hargaBarang', 'deskripsiBarang']

        widgets = {
            'namaBarang' : forms.TextInput(attrs={'class' : 'form-control'}),
            'jumlahStok' : forms.TextInput(attrs={'class' : 'form-control'}),
            'hargaBarang' : forms.TextInput(attrs={'class' : 'form-control'}),
            'deskripsiBarang' : forms.Textarea(attrs={'class' : 'form-control'}),
        }

detailBarang/views.py
from django.shortcuts import render, redirect
from .models import Barang
from django.http import JsonResponse

def detailBarang(request, barang_id):
    if 'nama' not in request.session:
        return redirect('main:home')
    user_type = request.session['role']
    
    if user_type == "pembeli" :
        response = {}
        post = Barang.objects.filter(id=barang_id)[0]
        response['post'] = post
        return render(request, 'detailBarang/postdetails.html', response)

manajemenpasar/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User 
from detailBarang.models import Barang
from .forms import BarangForm

# Create your views here.
def index(request):
    semuabarang = Barang.objects.all().order_by('-id')

    context = {
        'semuabarang':semuabarang,
    }

    return render(request, 'index.html', context)

def createbarang(request):
    if request.method == 'POST':
        form = BarangForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/manajemenpasar/')
    else:
        form = BarangForm()
    
    context = {
        'form': form
        }

    return render(request, 'createbarang.html', context)

def detailbarang(request, detail_id):
	detailBarang = Barang.objects.get(id=detail_id)
	harga = str(detailBarang.hargaBarang)[::-1]
	hargacopy = ""
	length = len(harga)
	count = len(harga)

	while count > 3:
		hargacopy += harga[length - count:length - count + 3] + "."
		count -= 3

	hargacopy += harga[length - count:length]
	harga = hargacopy[::-1]
	
	context = {
		'id':detailBarang.id,
		'namaBarang':detailBarang.namaBarang, 
		'jumlahStok':detailBarang.jumlahStok,
		'hargaBarang':harga,
		'deskripsiBarang':detailBarang.deskripsiBarang,
    }
	
	return render(request, 'detailbarang.html', context)

def deletebarang(request, delete_id):
    Barang.objects.filter(id=delete_id).delete()
    return redirect('/manajemenpasar/')

def updatebarang(request, update_id):
    instance = get_object_or_404(Barang, id=update_id)
    form = BarangForm(request.POST or None, instance=instance)

    if form.is_valid():
        form.save()
        return redirect('/manajemenpasar/')
    
    context = {
        'form': form
        }

    return render(request, 'createbarang.html', context)

manajemenpasar/templates/createbarang.html
{% extends 'navbar_1.html' %}
{% load static %}

{% block title %}
<title>Tambah Barang</title>
{% endblock title %}

{% block nav %}
    <a class="nav-link nav-item" href="#">➕Tambah Barang</a>
    <a class="nav-link nav-item" href="#"><img src="{% static 'img/User.png' %}" alt="" class="logo"></a>
{% endblock %}

{% block content %}
  <br><br><br><br><br>
  <div class="postform">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success btn-block">Submit</button>
    </form>
  </div>
{% endblock content %}

manajemenpasar/templates/detailbarang.html
{% extends 'navbar_1.html' %}
{% load static %}

{% block title %}
<title>Detail {{namaBarang}}</title>
{% endblock title %}

{% block nav %}
    <a class="nav-link nav-item" href="#">➕Tambah Barang</a>
    <a class="nav-link nav-item" href="#"><img src="{% static 'img/User.png' %}" alt="" class="logo"></a>
{% endblock %}

{% block content %}
    <br><br><br><br>
    <h3>Nama Barang : {{namaBarang}}</h3>
    <h3>Jumlah Stok : {{jumlahStok}} kg</h3>
    <h3>Harga Barang: Rp{{hargaBarang}}/kg </h3>
    <br>
    <h3>Deskripsi: </h3>
    <p>{{deskripsiBarang}}</p>
    <h5 style="text-align: center;">
        <a class="btn btn-success" href="{% url 'manajemenpasar:index'%}" title="">
            Back
        </a>
    </h5>
{% endblock %}

manajemenpasar/templates/index.html
{% extends 'navbar_1.html' %}
{% load static %}
{% block title %}
    <style>
    .container{
        margin-top:100px; 
    }
    .cards{
display: grid;
grid-template-columns: repeat(6, minmax(auto, 200px));
grid-column: 2 / span 6;
grid-gap: 30px;
margin-top: 20px;
margin-bottom: 20px;
}

.card{
border: 1px solid;
border-radius: 20px;
margin: 10px;
padding: 10px;
grid-column-end: span 2;
display: flex;
flex-direction: column;
}

.card:hover{
box-shadow: 10px 8px 16px 10px rgba(0,0,0,0.2);
right: 2px;
bottom: 3px;
}

.card-img-top{
border-radius: 10px 10px 0px 0px;
}
.judul{
    text-align: center;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Float cancel and delete buttons and add an equal width */
.cancelbtn, .deletebtn {
  float: left;
  width: 50%;
}

/* Add a color to the cancel button */
.cancelbtn {
  background-color: #ccc;
  color: black;
}

/* Add a color to the delete button */
.deletebtn {
  background-color: #f44336;
}



/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: #474e5d;
  padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}
 
/* The Modal Close Button (x) */
.close {
  position: absolute;
  right: 35px;
  top: 15px;
  font-size: 40px;
  font-weight: bold;
  color: #f1f1f1;
}

.close:hover,
.close:focus {
  color: #f44336;
  cursor: pointer;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

</style>
    <title>Atur Stok dan Barang</title>
{% endblock %}

{% block nav %}
    <a class="nav-link nav-item" href="/manajemenpasar/tambahbarang/">➕Tambah Barang</a>
    <a class="nav-link nav-item" href="#"><img src="{% static 'img/User.png' %}" alt="" class="logo"></a>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-start">
        <div class="col" style='margin: 10px;'></div>
        <div class="col">
          <h1 class='judul'>Atur Stok dan Barang</h1>
        </div>
        <div class="col"style='margin: 10px;'>
          
          <div class="row align-items-start">
            <button onclick="dlt()" id='delete' style='visibility: hidden;max-width: 50%;margin-left: 10px;' type="button" class="col btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                Delete
            </button>
            <div id="id01" class="modal">
                <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
                <form class="modal-content" action="/action_page.php">
                  <div class="container">
                    <h1>Delete Wishlist</h1>
                    <p>Apakah kamu yakin ingin menghapusnya?</p>
                  
                    <div class="clearfix">
                      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
                      <button type="button" onclick="hapus()" class="deletebtn">Delete</button>
                    </div>
                  </div>
                </form>
              </div>
            <!--<a onclick="dlt()" id='delete' style='visibility: hidden;'class="col"><h3>Delete</h3></a>-->
          </div>
          
        </div>
    </div>
    <div class="cards" id="cards">
        {% for item in semuabarang %}
        <div class="card" id='coba'style="background-color: white;visibility: visible;">
            <a  class= "content" href="{% url 'manajemenpasar:detailbarang' item.id%}" style="color: black; text-decoration: none;">
                <p style="text-align: center;margin-top: 7px;font-size: 25px;">{{item.namaBarang}}</p>
                
                <p style="font-size: 17px;">Rp {{item.hargaBarang}}/kg</p>
                
                <p style="font-size: 17px;">Tersedia {{item.jumlahStok}} kg</p>
                <div>
                    <div class="float-right">
                        <a style="font-size: 17px;" href="{% url 'manajemenpasar:updatebarang' item.id%}"><img class="logo" src="{% static 'img/Update.png' %}"></a>
                        <a style="font-size: 17px;" href="{% url 'manajemenpasar:deletebarang' item.id%}"><img class="logo" src="{% static 'img/Trashbin.svg' %}"></a>
                    </div>
                    <div class="float-right">
                        <div class="form-check" id='check' style='visibility: hidden;'>
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" style="width:20px;
                            height:20px;">
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}

    </div>
    

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    
function change()
{   
    var x = document.getElementById("edit");
    console.log(document.getElementById("check").style.visibility);
    if(x.innerHTML == '<h4>Edit</h4>'){
        document.getElementById("edit").innerHTML = "<h4>Cancel</h4>" ;
        document.getElementById("delete").style.visibility = 'visible';
        document.getElementById("check").style.visibility = 'visible';
    }
    else if(x.innerHTML == '<h4>Cancel</h4>'){
        document.getElementById("edit").innerHTML = "<h4>Edit</h4>" ;
        document.getElementById("delete").style.visibility = 'hidden';
        document.getElementById("check").style.visibility = 'hidden';
    }
}

function dlt()
{
    document.getElementById('id01').style.display='block';
    var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
    }
}

function hapus(){
    var modal = document.getElementById('id01');
    if(document.getElementById('flexCheckDefault').checked == true){
        document.getElementById('coba').style.visibility = 'hidden';
        modal.style.display = "none";
        document.getElementById('flexCheckDefault').style.visibility = 'hidden';
    }
    else{
        modal.style.display = "none"; 
    }
}
</script>
{% endblock %}